name: Build bcm2712 RPi 5B
on: [push]

jobs:
    build:
        name: Build Raspberry Pi 5 images
        runs-on: ubuntu-latest

        steps:
            - name: Maximize build space
              uses: AdityaGarg8/remove-unwanted-software@v1
              with:
                remove-android: 'true'
                remove-dotnet: 'true'
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/69b47c9a972e15056f94870d76d93a5146893f99/01-diskman.patch
                git apply 01-diskman.patch
                cd -
                cd  feeds/packages
                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/b35ba7a3aac1949bd6bbeaad065a0a93dc3c34f0/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch

                git apply 01-cpu.patch
                git apply 20-lxc.patch

                cd -
                sed -i "71s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "84s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "195s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "212s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                sed -i 's/default n/default y/g' feeds/packages/utils/dockerd/Config.in
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                cp .github/workflows/config.buildinfo .config
                make defconfig
                wget https://gist.githubusercontent.com/mj22226/23edc25efeb65ef69d8eb6598f4f8179/raw/29c862e3e2558852523f4e8edd5f3d0cc145067e/01-key.patch
                git apply 01-key.patch
                make download -j32
                rm 01-key.patch
                make -j$(nproc) 'IGNORE_ERRORS=n m'

            - name: Create release
              uses: ncipollo/release-action@v1.13.0
              with:
                allowUpdates: true

                name: Raspberry Pi 5 v6.8 Firmware Images
                tag: rpi-6.8.y
                replacesArtifacts: true
                prerelease: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: bin/targets/bcm27xx/bcm2712/*
